baseURL = "https://joga.blagorussia.ru/"
languageCode = "ru-ru"
title = "Новая йога"

[params]
  description = "Все совершенствуется и древнее учение йога тоже. На сайте Новая йога Вы найдете много материалов для физического и духовного совершенствования."
  author = "НП «Общественное благополучие Воронежа»"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
