baseURL = "https://joga.blagorussia.ru/"
languageCode = "ru-ru"
title = "Новая йога"

[params]
  description = "Новая йога"
  author = "НП «Общественное благополучие Воронежа»"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
